users:
  - name: admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/admin
    shell: /bin/bash
    lock_passwd: false
    plain_text_passwd: 'password'   
ssh_pwauth: true
disable_root: false
packages:
  - mariadb-server
  - php-mysqli
runcmd:
  - sudo mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;"